# logging
log_level = "DEBUG"  # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
log_file = "foldfusion_pipeline.log" # Name of the log file

# IO
#uniprot_ids = [
#    "Q8CA95",
#    "Q9QYJ6",
#    "Q9Y233",
#    "A0A287B941",
#    "A0A2R8N4P4",
#    "A0A3Q1MHJ4",
#]

uniprot_ids_file = "/local/mrueve/code/foldfusion-poc/uniprot_ids.txt"
# Path to the output directory
output_dir = "/home/stud2022/mrueve/Downloads/foldfusion_output" 

# dogsite3
dogsite3_executable = "/local/mrueve/.local/bin/dogsite3"

# siena db
siena_db_executable = "/local/mrueve/.local/bin/generate_siena_database"

# Either path to a siena database or path to pdb_files has to be valid
siena_db_database_path = "/home/stud2022/mrueve/Downloads/SienaDB/siena_db" 
pdb_directory = "/data/pdb/current/data/structures/all/pdb"
pdb_format = 0 # file format (0=.ent.gz, 1=pdb)

# siena
siena_executable = "/local/mrueve/.local/bin/siena"
siena_max_alignments = 1

# ligand extractor
ligand_extractor_executable = "/local/mrueve/.local/bin/ligand_extractor"

# jamda scorer
jamda_scorer_executable = "/local/mrueve/.local/bin/JamdaScorer"