# logging
log_level = "DEBUG"  # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
log_file = "foldfusion_pipeline.log" # Name of the log file

# IO
uniprot_ids = [
    "Q9Y233",
    "P22303",
    "Q8CA95",
    "Q9QYJ6",
    "A0A384DV92"
    ]
output_dir = "/home/stud2022/mrueve/Downloads/output"

# dogsite3
dogsite3_executable = "/home/stud2022/mrueve/local/bin/dogsite3"

# siena db
siena_db_executable = "/local/mrueve/opt/siena_1.3.0/generate_siena_database"
siena_db_database_path = "/home/stud2022/mrueve/local/projects/foldfusion-poc/siena_db" # Either path to a siena database or path to pdb_files has to be valid
pdb_directory = "/local/mrueve/data/PDBFiles_small/"
pdb_format = 0 # file format (0=.ent.gz, 1=pdb)

# siena
siena_executable = "/home/stud2022/mrueve/local/bin/siena"

# ligand extractor
ligand_extractor_executable = "/home/stud2022/mrueve/local/bin/ligand_extractor"

# jamda scorer
jamda_scorer_executable = "/home/stud2022/mrueve/local/bin/JamdaScorer"