[executables]
dogsite = "/home/stud2022/mrueve/local/bin/dogsite3"
siena = "/home/stud2022/mrueve/local/bin/siena"
ligand_extractor = "/home/stud2022/mrueve/local/bin/ligand_extractor"

[options]
dogsite = "--writeSiteResiduesEDF"
siena = ""
ligand_extractor = ""